# Generated by Django 5.1.4 on 2025-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(max_length=400)),
                ('main_desc', models.TextField()),
                ('about', models.TextField()),
                ('header1', models.CharField(max_length=200)),
                ('desc_1', models.TextField()),
                ('header2', models.CharField(max_length=200)),
                ('desc_2', models.TextField()),
                ('header3', models.CharField(max_length=200)),
                ('desc_3', models.TextField()),
                ('header4', models.CharField(max_length=200)),
                ('desc_4', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
